name: responsive_layout
description: Responsive breakpoints shell.
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
