//! Perpetum's lifecycle: the three files that must exist in a sandbox before
//! `perp run --requirement` will work. Mirrors what HarnessBench's adapter
//! does (`adapters/perpetum.py`): init is `perp init --root`, then links.md,
//! then a minted requirement row — Perpetum refuses work that is not on the
//! record.

use anyhow::{Context, Result};
use serde::Deserialize;
use std::fmt::Write as _;
use std::path::Path;

/// One model link plus the role table pointing every role at it.
#[derive(Debug, Clone, Deserialize)]
pub struct LinkConfig {
    pub name: String,
    pub kind: String,
    #[serde(default)]
    pub base_url: Option<String>,
    /// `{model}` is substituted with the round's model at trial time.
    pub model: String,
    #[serde(default)]
    pub auth_env: Option<String>,
    #[serde(default)]
    pub effort: Option<String>,
    /// (cache_hit, cache_miss, output) in USD per MTok.
    #[serde(default)]
    pub price: Option<(f64, f64, f64)>,
}

const ROLES: &[&str] = &[
    "planner", "coder", "gatefixer", "verifier", "chat", "compactor", "mutator", "classifier",
    "summarizer",
];

/// Render `.harness/links.md` with a single link serving every role.
pub fn links_md(link: &LinkConfig) -> String {
    let mut s = String::from(
        "# Links\n\nGenerated by Harpia for one benchmark trial. Do not edit.\n\n```perp-links\n",
    );
    let n = &link.name;
    let _ = writeln!(s, "link.{n}.kind = {}", link.kind);
    if let Some(url) = &link.base_url {
        let _ = writeln!(s, "link.{n}.base_url = {url}");
    }
    let _ = writeln!(s, "link.{n}.model = {}", link.model);
    if let Some(env) = &link.auth_env {
        let _ = writeln!(s, "link.{n}.auth_env = {env}");
    }
    if let Some(e) = &link.effort {
        let _ = writeln!(s, "link.{n}.effort = {e}");
    }
    s.push('\n');
    for role in ROLES {
        let _ = writeln!(s, "role.{role} = {n}");
    }
    if let Some((hit, miss, out)) = link.price {
        s.push('\n');
        let _ = writeln!(s, "price.{n}.cache_hit = {hit}");
        let _ = writeln!(s, "price.{n}.cache_miss = {miss}");
        let _ = writeln!(s, "price.{n}.output = {out}");
    }
    s.push_str("```\n");
    s
}

pub fn write_links_md(workspace: &Path, link: &LinkConfig) -> Result<()> {
    let dir = workspace.join(".harness");
    std::fs::create_dir_all(&dir)?;
    std::fs::write(dir.join("links.md"), links_md(link)).context("writing links.md")
}

/// Append a requirement row so `perp run --requirement <id>` has a record.
/// Creates the file with its table header when `perp init` did not.
pub fn mint_requirement(workspace: &Path, req_id: &str, title: &str) -> Result<()> {
    let dir = workspace.join(".harness").join("requirements");
    std::fs::create_dir_all(&dir)?;
    let path = dir.join("requirements.md");
    let mut body = match std::fs::read_to_string(&path) {
        Ok(b) => b,
        Err(_) => String::from("# Requirements\n\n| id | title |\n|---|---|\n"),
    };
    if !body.ends_with('\n') {
        body.push('\n');
    }
    let _ = writeln!(body, "| `{req_id}` | {} |", title.replace('|', "\\|"));
    std::fs::write(&path, body).context("writing requirements.md")
}

#[cfg(test)]
mod tests {
    use super::*;

    fn flash_link() -> LinkConfig {
        LinkConfig {
            name: "ds-fast".into(),
            kind: "deepseek".into(),
            base_url: Some("https://api.deepseek.com".into()),
            model: "deepseek-v4-flash".into(),
            auth_env: Some("DEEPSEEK_API_KEY".into()),
            effort: None,
            price: Some((0.0028, 0.14, 0.28)),
        }
    }

    #[test]
    fn links_md_has_fence_roles_and_price() {
        let md = links_md(&flash_link());
        assert!(md.contains("```perp-links\n"));
        assert!(md.contains("link.ds-fast.kind = deepseek"));
        assert!(md.contains("link.ds-fast.auth_env = DEEPSEEK_API_KEY"));
        assert!(md.contains("role.coder = ds-fast"));
        assert!(md.contains("role.verifier = ds-fast"));
        assert!(md.contains("price.ds-fast.cache_miss = 0.14"));
        assert!(md.trim_end().ends_with("```"));
    }

    #[test]
    fn mint_creates_then_appends() {
        let dir = std::env::temp_dir().join(format!("harpia-mint-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        mint_requirement(&dir, "R-1", "First task").unwrap();
        mint_requirement(&dir, "R-2", "Second | tricky").unwrap();
        let body =
            std::fs::read_to_string(dir.join(".harness/requirements/requirements.md")).unwrap();
        assert!(body.contains("| id | title |"));
        assert!(body.contains("| `R-1` | First task |"));
        assert!(body.contains("| `R-2` | Second \\| tricky |"));
        let _ = std::fs::remove_dir_all(&dir);
    }
}
