-- The split. Write the new tables, the backfill, and the replacement
-- orders_wide here. This file is applied immediately after schema.sql.

CREATE TABLE customers (
    id    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email text NOT NULL UNIQUE,
    name  text NOT NULL
);

CREATE TABLE orders (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_ref   text NOT NULL UNIQUE,
    customer_id integer NOT NULL REFERENCES customers (id),
    placed_on   date NOT NULL,
    status      text NOT NULL
);

CREATE TABLE order_lines (
    id               integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id         integer NOT NULL REFERENCES orders (id),
    line_no          integer NOT NULL,
    sku              text NOT NULL,
    quantity         integer NOT NULL,
    unit_price_cents integer NOT NULL,
    UNIQUE (order_id, line_no)
);

-- One customer per address; the wide table repeats the name on every line, so
-- take the one from the earliest order and fall back to the lowest ref.
INSERT INTO customers (email, name)
SELECT DISTINCT ON (w.customer_email) w.customer_email, w.customer_name
FROM orders_wide w
ORDER BY w.customer_email, w.placed_on, w.order_ref;

INSERT INTO orders (order_ref, customer_id, placed_on, status)
SELECT DISTINCT ON (w.order_ref) w.order_ref, c.id, w.placed_on, w.status
FROM orders_wide w
JOIN customers c ON c.email = w.customer_email
ORDER BY w.order_ref;

INSERT INTO order_lines (order_id, line_no, sku, quantity, unit_price_cents)
SELECT o.id, w.line_no, w.sku, w.quantity, w.unit_price_cents
FROM orders_wide w
JOIN orders o ON o.order_ref = w.order_ref;

-- Existing readers keep the name and the columns they already query.
DROP TABLE orders_wide;

CREATE VIEW orders_wide AS
SELECT o.order_ref,
       c.email            AS customer_email,
       c.name             AS customer_name,
       o.placed_on,
       o.status,
       l.line_no,
       l.sku,
       l.quantity,
       l.unit_price_cents
FROM orders o
JOIN customers   c ON c.id = o.customer_id
JOIN order_lines l ON l.order_id = o.id;
