-- 005: refunds.

CREATE TABLE refunds (
    id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id   integer NOT NULL REFERENCES payments (id) ON DELETE CASCADE,
    amount_cents integer NOT NULL CHECK (amount_cents > 0),
    refunded_on  date NOT NULL,
    reason       text NOT NULL
);

-- A payment can never be refunded for more than it was worth. That compares
-- across two tables, so a CHECK cannot express it.
CREATE FUNCTION refunds_within_payment() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
    paid      integer;
    refunded  integer;
BEGIN
    SELECT p.amount_cents INTO paid FROM payments p WHERE p.id = NEW.payment_id;

    SELECT coalesce(sum(r.amount_cents), 0) INTO refunded
    FROM refunds r
    WHERE r.payment_id = NEW.payment_id
      AND (TG_OP = 'INSERT' OR r.id <> NEW.id);

    IF refunded + NEW.amount_cents > paid THEN
        RAISE EXCEPTION
            'refunds against payment % would total %, more than the % that was paid',
            NEW.payment_id, refunded + NEW.amount_cents, paid
            USING ERRCODE = 'check_violation';
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER refunds_within_payment_trigger
    BEFORE INSERT OR UPDATE ON refunds
    FOR EACH ROW EXECUTE FUNCTION refunds_within_payment();

CREATE VIEW refund_summary AS
SELECT p.order_id,
       sum(p.amount_cents)::bigint AS paid_cents,
       coalesce((SELECT sum(r.amount_cents)
                 FROM refunds r
                 JOIN payments p2 ON p2.id = r.payment_id
                 WHERE p2.order_id = p.order_id), 0)::bigint AS refunded_cents,
       (sum(p.amount_cents)
        - coalesce((SELECT sum(r.amount_cents)
                    FROM refunds r
                    JOIN payments p2 ON p2.id = r.payment_id
                    WHERE p2.order_id = p.order_id), 0))::bigint AS net_cents
FROM payments p
GROUP BY p.order_id;
