-- Seating schema and a small venue's worth of data.
-- holds and bookings start empty; the workflow fills them.

CREATE TABLE events (
    id   integer PRIMARY KEY,
    name text NOT NULL,
    held_on date NOT NULL
);

CREATE TABLE seats (
    id       integer PRIMARY KEY,
    event_id integer NOT NULL REFERENCES events (id),
    row_label text NOT NULL,
    seat_no  integer NOT NULL,
    UNIQUE (event_id, row_label, seat_no)
);

CREATE TABLE holds (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id     integer NOT NULL REFERENCES events (id),
    customer_ref text NOT NULL,
    created_at   timestamp NOT NULL,
    expires_at   timestamp NOT NULL,
    state        text NOT NULL CHECK (state IN ('active', 'released', 'confirmed'))
);

CREATE TABLE hold_seats (
    hold_id bigint NOT NULL REFERENCES holds (id) ON DELETE CASCADE,
    seat_id integer NOT NULL REFERENCES seats (id),
    PRIMARY KEY (hold_id, seat_id)
);

CREATE TABLE bookings (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hold_id      bigint NOT NULL REFERENCES holds (id),
    event_id     integer NOT NULL REFERENCES events (id),
    customer_ref text NOT NULL,
    confirmed_at timestamp NOT NULL
);

CREATE TABLE booking_seats (
    booking_id bigint NOT NULL REFERENCES bookings (id) ON DELETE CASCADE,
    seat_id    integer NOT NULL REFERENCES seats (id),
    PRIMARY KEY (booking_id, seat_id)
);

INSERT INTO events (id, name, held_on) VALUES
    (1, 'Kolyma Quartet',  DATE '2024-09-14'),
    (2, 'Late Night Reel', DATE '2024-09-21');

-- Event 1: seats 101-105 are row A, 151-155 are row B. Event 2 mirrors it
-- at 201-205 and 251-255.
INSERT INTO seats (id, event_id, row_label, seat_no)
SELECT (e.id * 100) + CASE r.label WHEN 'A' THEN 0 ELSE 50 END + s.n,
       e.id, r.label, s.n
FROM (VALUES (1), (2)) AS e (id)
CROSS JOIN (VALUES ('A'), ('B')) AS r (label)
CROSS JOIN generate_series(1, 5) AS s (n);
